---
server_name: "test" # тут ваш домен
mysql_db: "wordpress"
mysql_user: "wordpress"
mysql_password: "WordpreSS0!"
nginx_vhosts:
  - listen: "80"
    server_name: "{{ ansible_facts.ansible_default_ipv4.address }} www.{{ ansible_facts.ansible_default_ipv4.address }}"
    filename: "{{ server_name }}.80.conf"

php_memory_limit: "128M"
php_max_execution_time: "90"
php_upload_max_filesize: "256M"
php_webserver_daemon: "nginx"
php_packages:
  - php
  - php-cli
  - php-common
  - php-gd
  - php-mbstring
  - php-pdo
  - php-xml
  - php-curl
  - php-gd
  - php-mbstring
  - php-xml
  - php-xmlrpc
  - php-soap
  - php-intl
  - php-zip
  - php-mysql
mysql_databases:
  - name: "{{ mysql_db }}"
    encoding: utf8
    collation: utf8_general_ci
mysql_users:
  - name: "{{ mysql_user }}"
    host: "%"
    password: "{{ mysql_password }}"
    priv: "wordpress.*:ALL"